package com.shouman.hawkAPI.model

enum class ResponseCode {
    SUCCESS,
    FIREBASE_CODE_NOT_VALID,
    NEW_USER_NOT_VALID,
    NEW_USER_INFO_NOT_VALID,
    COMPANY_ID_NOT_VALID,
    BRANCH_OBJECT_IS_NULL,
    BRANCH_ID_NOT_VALID,
    CUSTOMER_OBJECT_NOT_VALID
}